---
title: "Discussion - Week8"
author: "David Simbandumwe"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(matlib) 
```


# Example 8.2

Let X be a continuous random variable with values unformly distributed over the interval [0, 20].
(a) Find the mean and variance of X.
(b) Calculate P(|X −10| ≥ 2), P(|X −10| ≥ 5), P(|X −10| ≥ 9), and P (|X − 10| ≥ 20) exactly. How do your answers compare with those of Exercise 1? How good is Chebyshev’s Inequality in this case?


```{r}

a <- 0
b <- 20

mu <- (b+a) / 2
print(paste0('8.2a) mean = ', mu))
var  = (b-a)^2 / 12
print(paste0('8.) variance = ', round(var,4)))


```



```{r}

sd <- sqrt(var)
print(paste0('8.) standard deviation = ', round(sd,4)))


d <- mu + 2
c <- mu - 2
p2 <- (d-c) / (b-a)
print(paste0('P(|x-10| >= 2)k >= 2 = ' , round(p2,4) ))

d <- mu + 5
c <- mu - 5
p5 <- (d-c) / (b-a)
print(paste0('P(|x-10| >= 5)k >= 5 = ' , round(p5,4) ))


d <- mu + 9
c <- mu - 9
p9 <- (d-c) / (b-a)
print(paste0('P(|x-10| >= 9)k >= 9 = ', round(p9,4) ))

```










