---
title: "DATA605_w14_Taylor Series"
author: "David Simbandumwe"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
editor_options: 
  chunk_output_type: inline

---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
rm(list=ls())

```


```{r, include=FALSE}

library(matlib) 
library(ggplot2)

```



# Question 1
This week, we’ll work out some Taylor Series expansions of popular functions.
$$
f(x) = \frac{1}{(1-x)} \\
f(x) = e^{x} \\
f(x) = ln(1 + x) \\
f(x) = \sqrt{x}
$$

For each function, only consider its valid ranges as indicated in the notes when you are computing the Taylor Series expansion. Please submit your assignment as an R- Markdown document.


# Taylor Series Approximation

$$

P_{n}(x) = f(c) + f'(c)(x-c) + \frac{f''(c)}{(2!)} (x-c)^2 + \frac{f'''(c)}{(3!)} (x-c)^3...\frac{f^n(c)}{(n!)} (x-c)^n


$$




$$ 

f(x) = \frac{1}{(1-x)}  \\
f(x) = f(c) + f'(c)(x-c) + \frac{f''(c)}{(2!)} (x-c)^2 + \frac{f'''(c)}{(3!)} (x-c)^3 ...   \\
f(x) = \frac{1}{1-x} + \frac{1}{1-x} x + \frac{\frac{1}{1-x}}{(2!)} (x-c)^2 + \frac{\frac{1}{1-x}}{(3!)} (x-c)^3 ...  \\
evaluated \  at \ c = 0 \\
f(x) = \frac{1}{1-x} + \frac{1}{1-x} x + \frac{\frac{1}{1-x}}{(2!)} x^2 + \frac{\frac{1}{1-x}}{(3!)} x^3 ... \\
evaluated \ at  \ x = 0 \\
f(x) = \frac{1}{1-0} + \frac{1}{1-0} x + \frac{\frac{1}{1-0}}{(2!)} x^2 + \frac{\frac{1}{1-0}}{(3!)} x^3 ... \\
f(x) = 1 + x + x^2 + x^3 ... \\
generalized \\ 
\sum_{n = 0}^{\infty} x^n \\

$$



$$

f(x) = e^{x} \\
f(x) = e^x + e^x x + \frac{e^x}{(2!)} (x-c)^2 + \frac{e^x}{(3!)} (x-c)^3 ... \\
evaluated \  at \ c = 0 \\
f(x) = e^x + e^x x + \frac{e^x}{(2!)} x^2 + \frac{e^x}{(3!)} x^3 ...  \\
evaluated \ at  \ x = 0 \\
f(x) = 1 + x + \frac{ x^2}{(2!)} + \frac{x^3}{(3!)} ...   \\
generalized \\ 
e^x = \sum_{n = 0}^{\infty}  \frac{x^n}{(n!)} \\

$$





$$

f(x) = ln(1 + x) \\

f(x) = ln(1-x) + \frac{1}{x-1} + \frac{\frac{1}{(x-1)^2}}{(2!)} (x-c)^2 + \frac{\frac{2}{(x-1)^3}}{(3!)} (x-c)^3 + \frac{\frac{6}{(x-1)^4}}{(4!)} (x-c)^4 ...\\
evaluated \  at \ c = 0 \\
f(x) = ln(1-x) + \frac{1}{x-1} + \frac{\frac{1}{(x-1)^2}}{(2!)} x^2 + \frac{\frac{2}{(x-1)^3}}{(3!)} x^3 + \frac{\frac{6}{(x-1)^4}}{(4!)} x^4 ...\\
evaluated \ at  \ x = 0 \\
f(x) = 0 - 1 + \frac{x^2}{(2!)}  + \frac{2x^3}{(3!)} + \frac{6x^4 }{(4!)} ...\\
f(x) = 0 - 1 + \frac{x^2}{(2)}  - \frac{x^3}{(3)} + \frac{x^4 }{(4)} ...\\

generalized \\ 

ln(1 + x) = \sum_{n = 0}^{\infty} \frac{-1^n x^n}{n}

$$




$$

f(x) = \sqrt{x} \\
f(x) = \sqrt{x} + \frac{1}{2\sqrt{x}} (x-c) - \frac{\frac{1}{4x^(3/2)}}{(2!)} (x-c)^2 -  \frac{\frac{3}{8x^(5/2)}}{(3!)} (x-c)^3 ... \\
evaluated \  at \ c = 0 \\
f(x) = \sqrt{x} + \frac{1}{2\sqrt{x}} x - \frac{\frac{1}{4x^(3/2)}}{2} x^2 -  \frac{\frac{3}{8x^(5/2)}}{6} x^3 ... \\

evaluated \ at  \ x = 1 \\
f(0) = \sqrt{x} + \frac{1}{2\sqrt{x}} x - \frac{\frac{1}{4x^(3/2)}}{2} x^2 -  \frac{\frac{3}{8x^(5/2)}}{6} x^3 ... \\
f(0) = \sqrt{1} + \frac{1}{2\sqrt{1}} x - \frac{\frac{1}{4*1^(3/2)}}{2} x^2 -  \frac{\frac{3}{8*1^(5/2)}}{6} x^3 ... \\
f(0) = 1 + \frac{(x-1)}{2} - \frac{(x-1)^2}{8}  +  \frac{(x-1)^3}{16} ...   \\

generalized \\ 
\sqrt{x} = \sqrt{n} (-1 + x)^n

$$







