---
title: "DATA605_w4_eigenimagery"
author: "David Simbandumwe"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
rm(list=ls())

```


```{r, include=FALSE}

library(matlib) 
library(pracma)
library(stats)
library(magick)
library(imager)
library(OpenImageR)
library(jpeg)
library(imager)

```


With the attached data file, build and visualize  eigenimagery that accounts for 80% of the variability.  Provide full R code and discussion.


```{r}
#Get the list of all images
file_info = list.files(path = "./Homework/data/w4/jpg", pattern = ".jpg", full.names = T)

#Get the dataframe with info
file_info = image_info(image_read(file_info))

#Attach the file names
file_info$fileName = list.files(path = "./Homework/data/w4/jpg", pattern = ".jpg")

# set dimensions
height <- 1200
width <- 2500
scale <- 10


# create img array
img_array <- array(rep(0, length(file_info) * height / scale * width / scale * 3)
					, dim = c(nrow(file_info)
				  	, height/scale, width/scale
				  	,3))


# read img array from files
for (i in 1:nrow(file_info)) {
	tmp <- readJPEG(paste0("./Homework/data/w4/jpg/", file_info$fileName[i]))
	tmp <- resizeImage(tmp,height/scale, width/scale, method = "nearest", normalize_pixels = FALSE)
	img_array[i,,,] <- array(as.cimg(tmp), dim=c(1, height/scale, width/scale,3))
}


# print resized images
for (i in 1:nrow(img_array)) {
	plot(as.cimg(img_array[i,,,]))
}


```





```{r}

# create new data array and set dimesions
data <- img_array
dim(data) <- c(nrow(img_array), height*width*3/scale^2)

# calc princomp
pcomp <- princomp(t(as.matrix(data)), scores=TRUE, cor=TRUE)
pcomp_all <- t(pcomp$scores)
dim(pcomp_all) <- c(nrow(img_array), height/scale, width/scale, 3)

# summary stats
summary(pcomp)



```

```{r}

# print results
for (i in 1:nrow(pcomp_all)){
	plot(as.cimg(pcomp_all[i,,,]))  
}

```


<br><br>
<b><i>Please show your work using an R-markdown document. Please name your assignment submission with your first initial and last name.</i></b>

