---
title: "Scratch"
author: "David Simbandumwe"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(matlib) 
```


# Week 1

```{r}

A <- matrix(c(3,2,-1,2,-2,0.5,-1,4,-1), nrow=3, ncol=3)
A

b <- matrix(c(1,-2,0))
b

solve(A,b)


```



```{r}

A <- matrix(c(2,1,1,-2, -4,-2,-2,4, 3,-2,1,0, 0,14,2,-12, 1,4,1,1), nrow=4, ncol=5)
A

b <- matrix(c(6,15,-1,7))
b

solve(A,b)



```





```{r}

A <- matrix(c(7/15,6/15,2/15, 6/15,4/15,5/15, 2/15,5/15,8/15), nrow=3, ncol=3)
A

b <- matrix(c(380,500,620))
b

solve(A,b)
Solve(A,b)
showEqn(A, b)
#plotEqn(A,b)

 #A[2,] * b 

```





```{r}
#2x + 3y = −8, x − y = 6.

A <- matrix(c(2,1,3,-1), nrow=2, ncol=2)
A

b <- matrix(c(-8,6))
b

solve(A,b)

showEqn(A, b)
plotEqn(A,b)
```






```{r}
# a11 = 1 a21 = 1 a31 = 3
# a12 = 2 a22 = 1 a32 = 1
# a13 = 0 a23 = 1 a33 = 5
# a14 = 1 a24 = −1 a34 = −7
# b1 = 7 b2 = 3 b3 = 1

A <- matrix(c(1,1,3,2,1,1,0,1,5,1,-1,-7), nrow=3, ncol=4)
A

b <- c(7,3,1)
b


showEqn(A, b)
Solve(A,b)

```





```{r}

# 2x1 + 3x2 = 3 
# x1 − x2 = 4

A <- matrix(c(2,1,3,-1), nrow=2, ncol=2)
b <- c(3,4)

showEqn(A, b)
Solve(A,b)
plotEqn(A,b)



```







```{r}

A <- matrix(c(1,1,2,2,3,6,2,3,5), nrow=3, ncol=3)
b <- c(4,5,6)

showEqn(A, b)
Solve(A,b, verbose=FALSE)

x <- solve(A,b)
x

A%*%x

```



```{r}

# 3x + 2y = 1
# x−y=2
# 4x + 2y = 2


A <- matrix(c(3,1,4, 2,-1,2), nrow=3, ncol=2)
b <- c(1,2,2)

showEqn(A, b)
Solve(A,b, verbose=TRUE)



```







```{r}

A <- matrix(c(2,-3,1, 1,4,1, 7,-5,4, -7,-6,-5), nrow=3,ncol=4)
b <- c(2,3,2)

showEqn(A, b)
Solve(A,b, verbose=FALSE)


```



```{r}
library('pracma')
```



```{r}

A <- matrix(c(2,5,3,5, 0,1,0,3, 3,2,1,2, 2,4,2,1),4)
det(A)


```









